keys:
  # Shared keys
  - &github_key age1lvgr9hjh4t9qw0w79hxkpygqa9d4temq70lalksupe7tq38zm3jqy4u99x
  - &homelab_key age1qnmt7leg98qd75szl3sytd4clvj48t8tnqednjl9d8hszqjp7dmsge4pq4

  # Machine keys
  - &devil age1k9rk8rlcccpdw5gslm3rsw4t2nvvluwa77d8j8vrmmyvft047pys32l0xt
  - &daredevil age1t363efchn7yahsnwg65vnkculygqzk9vacl55eyd3e47a0mw29dqw3mquh
  - &homelab_one age1lkeyp8n597el6jeeyremqaayrlr5j8zqln92ddr0zxs2h9khuqdq0wmgwe
  - &old_devil age1y8ruw5f80t4ga4uuqsqmx85uacf0yn37ly5hdmxe0z9q083udpmsw5hpfx
  - &lucifer age1rpyc4y7pensd2nkauf46sm6gpamrngp4vtymeu83tlmkhkj96qxqhgxmav
creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
    - age:
      - *github_key
      - *homelab_key
      - *devil
      - *daredevil
      - *homelab_one
      - *old_devil
      - *lucifer

  - path_regex: secrets/.*\.conf$
    key_groups:
    - age:
      - *github_key
      - *homelab_key
      - *devil
      - *daredevil
      - *homelab_one
      - *old_devil
      - *lucifer
