name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: nix flake check
        run: |
          nix flake check --print-build-logs \
            --option accept-flake-config true

      - name: Check formatting (alejandra)
        run: |
          nix run nixpkgs#alejandra -- --check .