apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://127.0.0.1:9090
    isDefault: true
    access: proxy
  - name: Loki
    type: loki
    url: http://127.0.0.1:3100
    access: proxy
